# -*- coding: utf-8 -*-
"""BERT-based PDF Question Answering Tool.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1knzSDdtoR2kCl6yhwgXMxPpupgXEK8Fo

Step 1: Install Required Libraries
"""

!pip install transformers torch PyPDF2 -q

"""Step 2: Upload Your PDF"""

from google.colab import files
uploaded = files.upload()   # select file3.pdf

"""Step 3: Extract Text from the PDF"""

import PyPDF2

def extract_text_from_pdf(pdf_path):
    text = ""
    with open(pdf_path, "rb") as f:
        reader = PyPDF2.PdfReader(f)
        for page in reader.pages:
            page_text = page.extract_text()
            if page_text:
                text += page_text + "\n"
    return text

context = extract_text_from_pdf("file3.pdf")
print(context[:1000])   # preview

"""Step 4: Load a Pre-trained BERT QA Model

We'll use bert-large-uncased-whole-word-masking-finetuned-squad
"""

from transformers import pipeline

qa_pipeline = pipeline(
    "question-answering",
    model="bert-large-uncased-whole-word-masking-finetuned-squad",
    tokenizer="bert-large-uncased-whole-word-masking-finetuned-squad"
)

"""Step 5: Handle Long PDFs (Chunking)

BERT has a 512-token limit. Splitting context into overlapping chunks and then pick the best answer
"""

def chunk_text(text, chunk_size=2000, overlap=200):
    chunks = []
    start = 0
    while start < len(text):
        end = min(start + chunk_size, len(text))
        chunks.append(text[start:end])
        start += chunk_size - overlap
    return chunks

def answer_question(question, context):
    chunks = chunk_text(context)
    best = {"score": 0, "answer": ""}
    for chunk in chunks:
        try:
            result = qa_pipeline(question=question, context=chunk)
            if result["score"] > best["score"]:
                best = result
        except Exception:
            continue
    return best["answer"], best["score"]

"""Step 6: Ask the Questions"""

questions = [
    "What is the capital city of Bangladesh?",
    "Which river is considered the lifeline of Bangladesh?",
    "In which year did Bangladesh gain independence?",
    "What is the official language of Bangladesh?",
    "What is the name of the world's largest mangrove forest located in Bangladesh?",
    "Which currency is used in Bangladesh?",
    "What is the national animal of Bangladesh?"
]

for q in questions:
    ans, score = answer_question(q, context)
    print(f"Q: {q}\nA: {ans}  (confidence: {score:.2f})\n")

"""Step 7: Interactive Mode"""

while True:
    q = input("Ask a question (or 'quit'): ")
    if q.lower() == "quit":
        break
    ans, score = answer_question(q, context)
    print(f"Answer: {ans} (confidence: {score:.2f})\n")